# Initializes RAD Studio / Delphi environment variables for MSBuild in this PowerShell session.
# Generated by: adm --init-delphi

# IMPORTANT: dot-source this script to keep env in the current session:
#   . .\tools\init_delphi.ps1 -Platform Win32

param(
  [ValidateSet('Win32','Win64','Linux64')]
  [string]$Platform = 'Win64'
)

$ErrorActionPreference = 'Stop'
$rsvars = @'
D:\USESoft\RAD_Pascal\bin\rsvars.bat
'@.Trim()
$rsvars64 = @'
D:\USESoft\RAD_Pascal\bin64\rsvars64.bat
'@.Trim()
$bat = if ($Platform -in @('Win64','Linux64')) { $rsvars64 } else { $rsvars }
if (-not (Test-Path -LiteralPath $bat)) {
  Write-Error "rsvars script not found: $bat"
}

$cmdLine = ('call "{0}" >nul && set' -f $bat)
$envBlock = & cmd.exe /d /s /c $cmdLine
foreach ($line in $envBlock) {
  $idx = $line.IndexOf('=')
  if ($idx -lt 1) { continue }
  $name = $line.Substring(0, $idx)
  $value = $line.Substring($idx + 1)
  if ($name -eq 'PROMPT') { continue }
  [System.Environment]::SetEnvironmentVariable($name, $value, 'Process')
}

Write-Host "[OK] Delphi environment initialized for $Platform."
Write-Host "default_platform=Win64"
Write-Host "detected_root=D:\USESoft\RAD_Pascal"
Write-Host "Example: .\\tools\\build_delphi_msbuild.ps1 -Dpr delphi\\ADIDInstallerFMX.dpr -Platform $Platform -Config Release"
Write-Host "Linux note: FMX only; typically also pass -Profile (Remote Profile name)."
Write-Host ("dcc32=" + [bool](Get-Command dcc32 -ErrorAction SilentlyContinue))
Write-Host ("BDS=" + $env:BDS)
